[[tree_sitter_fortran]]
arch = "aarch64"
git-tree-sha1 = "90bf0c0c6b4d2dd38947de7ab1222bc537f5ded5"
os = "macos"

    [[tree_sitter_fortran.download]]
    sha256 = "359a0ebfbf31d1a13c8184d11478f43b973d1c9be48f811b9f41e18d2377f7b5"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.aarch64-apple-darwin.tar.gz"
[[tree_sitter_fortran]]
arch = "aarch64"
git-tree-sha1 = "47d6a2fa55715466f08abd347e73d3d3bf775bdf"
libc = "glibc"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "eeda1988eeded1e3d1f063118a9c11371d078d16a999180c2d797cfc0beb541f"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.aarch64-linux-gnu.tar.gz"
[[tree_sitter_fortran]]
arch = "aarch64"
git-tree-sha1 = "b99016b393acf7e6820c5cc5003b7d8531cc9848"
libc = "musl"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "94c43e4d07d231ce777b4fe23bea5ba249636937294f7d41f0d5ba6411615f69"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.aarch64-linux-musl.tar.gz"
[[tree_sitter_fortran]]
arch = "aarch64"
git-tree-sha1 = "badee0512e6cf6514a8ce3765690eb59cac2541d"
os = "freebsd"

    [[tree_sitter_fortran.download]]
    sha256 = "fa97eb1448358aaaf0841cf6e5a98ed4a443a22cef95e8ae31a75efddd04f42b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.aarch64-unknown-freebsd.tar.gz"
[[tree_sitter_fortran]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b2393b1efd3b8dec901fabab2feb7e3fbc2bb271"
libc = "glibc"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "72f59e5ed70dbc07312841716db04b968208269b2b1f816d9436e24f006e8116"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.armv6l-linux-gnueabihf.tar.gz"
[[tree_sitter_fortran]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eaf8f346fb357fcfe08b5c3f003fd87a0cea2034"
libc = "musl"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "c393d7644f7b1c4bbc620e6aef768fd2fd8df086bdb875dd340b88b1f9356058"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.armv6l-linux-musleabihf.tar.gz"
[[tree_sitter_fortran]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d5dee3ed8ed2062242fae65c6df68e399d138be4"
libc = "glibc"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "f650dcaad18de8d32d71be24c592dc878f3c7ec979094865156b3bb738448233"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.armv7l-linux-gnueabihf.tar.gz"
[[tree_sitter_fortran]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2192bbb08cf6ca9905a432a2d5d420dc7484b98"
libc = "musl"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "506381e8eb66d6a590d04bbf18f8a49fb563198af6b5be055401c47dbc85d723"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.armv7l-linux-musleabihf.tar.gz"
[[tree_sitter_fortran]]
arch = "i686"
git-tree-sha1 = "b3a3b2aa1d1d30b74401bfec7ad5f7708edecc7f"
libc = "glibc"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "28d92e271fcd23c6f89f4c0256cbc731b19e67c083f9b93919669eb862aebaf2"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.i686-linux-gnu.tar.gz"
[[tree_sitter_fortran]]
arch = "i686"
git-tree-sha1 = "392afd8abad0c7ec9bb8c6bdadacded0b875c065"
libc = "musl"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "3821a4463bb099b8f582b247ea531313047a5e8a3183a6a85777de9285472193"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.i686-linux-musl.tar.gz"
[[tree_sitter_fortran]]
arch = "i686"
git-tree-sha1 = "1185bc29e4c6e3809ba0a4fdcd3ea2b8336a9500"
os = "windows"

    [[tree_sitter_fortran.download]]
    sha256 = "57dc6fcbbbbd585d10ab2b1effe0af3b47867873e586081fcd72c7b4658cdba9"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.i686-w64-mingw32.tar.gz"
[[tree_sitter_fortran]]
arch = "powerpc64le"
git-tree-sha1 = "97ddb3f1d416bce042e4b942a737295164bc9b60"
libc = "glibc"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "f7260f7fc2f6308360aa4e6e61ddc4107daa75403944e4cd93197ad048fe364c"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.powerpc64le-linux-gnu.tar.gz"
[[tree_sitter_fortran]]
arch = "riscv64"
git-tree-sha1 = "a043c113e532c7f141a782095f5eeb6a380eb92b"
libc = "glibc"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "8a804bd31b7fb4446f79529c60c165886cf70eaebef19c7689cb0175aff07dab"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.riscv64-linux-gnu.tar.gz"
[[tree_sitter_fortran]]
arch = "x86_64"
git-tree-sha1 = "c46f9e7cd8d412666fd645ebdfdd9b01ee049b5e"
os = "macos"

    [[tree_sitter_fortran.download]]
    sha256 = "e2942289a37c5434abd3073db6e088dfe8dd2efe0e8540539e30dbaba31a2598"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.x86_64-apple-darwin.tar.gz"
[[tree_sitter_fortran]]
arch = "x86_64"
git-tree-sha1 = "6eff51f691030ec38cdc16606f3cccc612a4ab61"
libc = "glibc"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "4dd75719c0ed43b327e89f8b8ff1a2bda4aab94973d360f47515ce47bfb21f3b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.x86_64-linux-gnu.tar.gz"
[[tree_sitter_fortran]]
arch = "x86_64"
git-tree-sha1 = "a2d0ff27a7e6cfb45a9f14192ec98ce0682c0561"
libc = "musl"
os = "linux"

    [[tree_sitter_fortran.download]]
    sha256 = "03e2c92c72bb84760907beb4a62d81880e717cdc81bbe585c029c19f9086fccf"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.x86_64-linux-musl.tar.gz"
[[tree_sitter_fortran]]
arch = "x86_64"
git-tree-sha1 = "c86700d9be56c11e21f91f8c04609f703ef461db"
os = "freebsd"

    [[tree_sitter_fortran.download]]
    sha256 = "b68d86c396984f8c874456471c1b09feac46cf361b27bcf959c0cac2f21c2d27"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.x86_64-unknown-freebsd.tar.gz"
[[tree_sitter_fortran]]
arch = "x86_64"
git-tree-sha1 = "d4ab22e2065127f36333097c6373a682628806cb"
os = "windows"

    [[tree_sitter_fortran.download]]
    sha256 = "6fb71da2f960a9d60b9769261679867734c9ab3a516db8ce9d8224de0e3899c6"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_fortran_jll.jl/releases/download/tree_sitter_fortran-v0.6.0+0/tree_sitter_fortran.v0.6.0.x86_64-w64-mingw32.tar.gz"
