# Autogenerated wrapper script for tree_sitter_fortran_jll for aarch64-apple-darwin
export libtreesitter_fortran

JLLWrappers.@generate_wrapper_header("tree_sitter_fortran")
JLLWrappers.@declare_library_product(libtreesitter_fortran, "@rpath/libtree-sitter-fortran.14.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_fortran,
        "lib/libtree-sitter-fortran.14.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
