# Autogenerated wrapper script for tree_sitter_fortran_jll for x86_64-w64-mingw32
export libtreesitter_fortran

JLLWrappers.@generate_wrapper_header("tree_sitter_fortran")
JLLWrappers.@declare_library_product(libtreesitter_fortran, "libtree-sitter-fortran.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_fortran,
        "bin\\libtree-sitter-fortran.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
